### ISSUE TITLE
ceph-osd should deploy after storage-connector on a node when both charms are deployed

### ISSUE THREAD

**Issue by sudeephb** [canonical/charm-storage-connector#9]
When the disk needed by ceph-osd charm comes from a iscsi or fiber channel connection configured by storage-connector, there needs to be logic in the charm to run storage-connector before ceph-osd. At the moment, ceph-osd can run first and try to grab a disk that does not exist yet. This leads to failure during the deployment

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2021-12-07T00:25:26Z
 * owner: [camille.rodriguez](https://launchpad.net/~camille.rodriguez)
 * assignee: [None](https://launchpad.net/~None)
 
 
 * the launchpad [url](https://bugs.launchpad.net/bugs/1953408)

**Comment by Pjack** [comment]
There is no integration with Ceph OSD charm and storage-connector charm. So I also think we should close this issue.
